"""report_reward_item_redemption

Revision ID: 5e48a8596f09
Revises: c34aa729af7c
Create Date: 2026-08-20 14:01:59.043550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e48a8596f09'
down_revision: Union[str, None] = 'c34aa729af7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_redemption',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_redemption'))
    )
    op.create_index(op.f('ix_report_redemption_user_id'), 'report_redemption', ['user_id'], unique=False)
    op.create_table('report_reward_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_reward_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_reward_item')
    op.drop_index(op.f('ix_report_redemption_user_id'), table_name='report_redemption')
    op.drop_table('report_redemption')
    # ### end Alembic commands ###
