"""email template tracking options

Revision ID: 3afe38a93073
Revises: 8452d09fcd36
Create Date: 2026-08-17 19:59:37.427997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afe38a93073'
down_revision: Union[str, None] = '8452d09fcd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_template', sa.Column('track_pixel', sa.Integer(), nullable=False, comment='嵌入1x1像素统计打开'))
    op.add_column('email_template', sa.Column('track_link', sa.Integer(), nullable=False, comment='链接携带追踪token'))
    op.add_column('email_template', sa.Column('track_attach', sa.Integer(), nullable=False, comment='附件打开追踪'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_template', 'track_attach')
    op.drop_column('email_template', 'track_link')
    op.drop_column('email_template', 'track_pixel')
    # ### end Alembic commands ###
