"""campaign training_redirect_url 自定义跳转页

Revision ID: 345903539c7b
Revises: 5e48a8596f09
Create Date: 2026-08-20 23:09:02.545704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '345903539c7b'
down_revision: Union[str, None] = '5e48a8596f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('training_redirect_url', sa.String(length=512), nullable=True, comment='url 模式：提交后 302 跳转的自定义页面'))
    op.alter_column('campaign', 'training_policy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               comment='redirect/popup/none/url',
               existing_comment='redirect/popup/none',
               existing_nullable=False)
    op.alter_column('platform_setting', 'setting_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='logo/name/copyright/retention_days/disclaimer/ai_switches',
               existing_comment='logo/name/copyright/pixel_enabled/retention_days/disclaimer/ai_switches',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform_setting', 'setting_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='logo/name/copyright/pixel_enabled/retention_days/disclaimer/ai_switches',
               existing_comment='logo/name/copyright/retention_days/disclaimer/ai_switches',
               existing_nullable=False)
    op.alter_column('campaign', 'training_policy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               comment='redirect/popup/none',
               existing_comment='redirect/popup/none/url',
               existing_nullable=False)
    op.drop_column('campaign', 'training_redirect_url')
    # ### end Alembic commands ###
