"""initial schema

Revision ID: 1cb3bdd0fa3e
Revises: 
Create Date: 2026-08-16 09:44:40.268421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1cb3bdd0fa3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_draft',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('biz_type', sa.String(length=24), nullable=False, comment='email_template/landing_page/course/report_summary'),
    sa.Column('biz_id', sa.BigInteger(), nullable=True, comment='确认入库后回填'),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False, comment='draft/approved/discarded'),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_draft'))
    )
    op.create_index(op.f('ix_ai_draft_biz_type'), 'ai_draft', ['biz_type'], unique=False)
    op.create_table('ai_message',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False, comment='user/assistant/system'),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_message'))
    )
    op.create_index(op.f('ix_ai_message_session_id'), 'ai_message', ['session_id'], unique=False)
    op.create_table('ai_provider',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False, comment='openai/claude/wenxin/tongyi/local'),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('api_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.String(length=4000), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('data_outbound', sa.Integer(), nullable=False, comment='0=数据不外发(仅本地模型)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_provider'))
    )
    op.create_table('ai_session',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('page_context', sa.JSON(), nullable=True, comment='页面上下文快照'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_session'))
    )
    op.create_index(op.f('ix_ai_session_account_id'), 'ai_session', ['account_id'], unique=False)
    op.create_table('ai_usage_stat',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_stat')),
    sa.UniqueConstraint('provider_id', 'stat_date', name='uq_ai_usage_provider_date')
    )
    op.create_table('attachment_download_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('payload_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False, comment='download/delete'),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment_download_log'))
    )
    op.create_index(op.f('ix_attachment_download_log_payload_id'), 'attachment_download_log', ['payload_id'], unique=False)
    op.create_table('attachment_payload',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False, comment='macro_doc/exe/other'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='MinIO隔离桶'),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment_payload'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('account_name', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=False, comment='campaign/template/channel/ai/license...'),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True, comment='变更摘要/前后值'),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_account_id'), 'audit_log', ['account_id'], unique=False)
    op.create_index(op.f('ix_audit_log_module'), 'audit_log', ['module'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False, comment='mail/sms/social/usb'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='draft/scheduled/sending/running/paused/completed/terminated'),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('landing_page_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('domain_id', sa.BigInteger(), nullable=True),
    sa.Column('target_mode', sa.String(length=16), nullable=True, comment='dept/tag/csv/mix'),
    sa.Column('target_snapshot', sa.JSON(), nullable=True, comment='圈选条件快照'),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=8), nullable=False, comment='now/timed'),
    sa.Column('schedule_at', sa.DateTime(), nullable=True),
    sa.Column('batch_count', sa.Integer(), nullable=False),
    sa.Column('batch_interval_min', sa.Integer(), nullable=False),
    sa.Column('randomize_content', sa.Integer(), nullable=False, comment='内容随机化'),
    sa.Column('time_jitter_sec', sa.Integer(), nullable=False, comment='发送时刻抖动'),
    sa.Column('pixel_degrade', sa.Integer(), nullable=False, comment='追踪像素降级'),
    sa.Column('training_policy', sa.String(length=8), nullable=False, comment='redirect/popup/none'),
    sa.Column('course_ids', sa.JSON(), nullable=True, comment='关联培训课程'),
    sa.Column('force_training_rules', sa.JSON(), nullable=True, comment='强制培训触发条件'),
    sa.Column('auth_confirmed', sa.Integer(), nullable=False, comment='授权确认勾选'),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign'))
    )
    op.create_index(op.f('ix_campaign_creator_id'), 'campaign', ['creator_id'], unique=False)
    op.create_index(op.f('ix_campaign_schedule_at'), 'campaign', ['schedule_at'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_table('campaign_alert',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False, comment='pwd_submit/exec_user/dept_threshold/fast_submit/repeat_n'),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('handled', sa.Integer(), nullable=False),
    sa.Column('handled_by', sa.BigInteger(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_alert'))
    )
    op.create_index(op.f('ix_campaign_alert_campaign_id'), 'campaign_alert', ['campaign_id'], unique=False)
    op.create_table('campaign_batch',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('plan_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False, comment='pending/sending/done/failed'),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_batch')),
    sa.UniqueConstraint('campaign_id', 'batch_no', name='uq_campaign_batch')
    )
    op.create_index(op.f('ix_campaign_batch_campaign_id'), 'campaign_batch', ['campaign_id'], unique=False)
    op.create_table('campaign_stat',
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('delivered_cnt', sa.Integer(), nullable=False),
    sa.Column('open_cnt', sa.Integer(), nullable=False),
    sa.Column('click_cnt', sa.Integer(), nullable=False),
    sa.Column('submit_cnt', sa.Integer(), nullable=False),
    sa.Column('report_cnt', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_campaign_stat'))
    )
    op.create_table('campaign_target',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False, comment='唯一追踪令牌'),
    sa.Column('send_status', sa.String(length=12), nullable=False, comment='pending/sent/delivered/bounced/failed'),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('first_open_at', sa.DateTime(), nullable=True),
    sa.Column('last_open_at', sa.DateTime(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('first_click_at', sa.DateTime(), nullable=True),
    sa.Column('submit_flag', sa.Integer(), nullable=False),
    sa.Column('submit_at', sa.DateTime(), nullable=True),
    sa.Column('report_flag', sa.Integer(), nullable=False),
    sa.Column('report_at', sa.DateTime(), nullable=True),
    sa.Column('fingerprint_id', sa.BigInteger(), nullable=True),
    sa.Column('training_assignment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_target')),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_target_user'),
    sa.UniqueConstraint('token', name=op.f('uq_campaign_target_token'))
    )
    op.create_index(op.f('ix_campaign_target_campaign_id'), 'campaign_target', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_target_user_id'), 'campaign_target', ['user_id'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False, comment='video/article/pdf/interactive'),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('content_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=False, comment='builtin/custom/ai'),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.create_table('email_template',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scene', sa.String(length=16), nullable=False, comment='finance/hr/system/holiday/prize/security'),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('html_body', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True, comment='使用的变量清单'),
    sa.Column('source', sa.String(length=12), nullable=False, comment='builtin/custom/ai/cloned'),
    sa.Column('status', sa.String(length=12), nullable=False, comment='draft/approved'),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_template'))
    )
    op.create_table('emp_dept',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False, comment='/1/5/12/ 加速祖先查询'),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True, comment='manual/ldap/wecom/dingtalk/feishu'),
    sa.Column('source_id', sa.String(length=128), nullable=True, comment='外部系统ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emp_dept')),
    sa.UniqueConstraint('source', 'source_id', name='uq_emp_dept_source')
    )
    op.create_table('emp_group',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emp_group'))
    )
    op.create_table('emp_group_member',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_emp_group_member'))
    )
    op.create_table('emp_risk_profile',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False, comment='综合风险分0-100'),
    sa.Column('email_recognize', sa.Integer(), nullable=False, comment='邮件识别维度'),
    sa.Column('link_click', sa.Integer(), nullable=False, comment='链接点击维度'),
    sa.Column('pwd_submit', sa.Integer(), nullable=False, comment='密码提交维度'),
    sa.Column('attach_run', sa.Integer(), nullable=False, comment='附件下载维度'),
    sa.Column('report_awareness', sa.Integer(), nullable=False, comment='举报意识维度'),
    sa.Column('phish_count', sa.Integer(), nullable=False, comment='历史中招次数'),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('training_completion', sa.Numeric(precision=5, scale=2), nullable=False, comment='培训完成度%'),
    sa.Column('risk_level', sa.Integer(), nullable=False, comment='1低(0-30) 2中(31-70) 3高(71-100)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_emp_risk_profile'))
    )
    op.create_table('emp_tag',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emp_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_emp_tag_name'))
    )
    op.create_table('emp_user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(length=64), nullable=True, comment='工号'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('mobile_enc', sa.LargeBinary(), nullable=True, comment='加密存储,展示掩码'),
    sa.Column('dept_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False, comment='1在职 0离职停用'),
    sa.Column('initial_risk', sa.Integer(), nullable=False, comment='初始风险值0-100'),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emp_user')),
    sa.UniqueConstraint('email', name=op.f('uq_emp_user_email'))
    )
    op.create_index(op.f('ix_emp_user_dept_id'), 'emp_user', ['dept_id'], unique=False)
    op.create_table('emp_user_tag',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name=op.f('pk_emp_user_tag'))
    )
    op.create_table('exam_paper',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_paper'))
    )
    op.create_table('exam_paper_question',
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('paper_id', 'question_id', name=op.f('pk_exam_paper_question'))
    )
    op.create_table('exam_question',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False, comment='single/multi/judge'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.String(length=32), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_question'))
    )
    op.create_table('exam_record',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_record'))
    )
    op.create_index(op.f('ix_exam_record_paper_id'), 'exam_record', ['paper_id'], unique=False)
    op.create_index(op.f('ix_exam_record_user_id'), 'exam_record', ['user_id'], unique=False)
    op.create_table('fingerprint',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('fp_hash', sa.String(length=32), nullable=False, comment='Canvas/WebGL/字体/时区等合成'),
    sa.Column('guess_user_id', sa.BigInteger(), nullable=True, comment='推断关联员工'),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprint')),
    sa.UniqueConstraint('fp_hash', name=op.f('uq_fingerprint_fp_hash'))
    )
    op.create_table('landing_form_field',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('sensitive_flag', sa.Integer(), nullable=False, comment='1=口令类,脱敏存储'),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing_form_field'))
    )
    op.create_index(op.f('ix_landing_form_field_page_id'), 'landing_form_field', ['page_id'], unique=False)
    op.create_table('landing_page',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False, comment='mail_login/oa_login/pan_auth/custom/cloned'),
    sa.Column('slug', sa.String(length=48), nullable=False, comment='URL: /p/{slug}'),
    sa.Column('html_content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('page_schema', sa.JSON(), nullable=True, comment='构建器区块描述'),
    sa.Column('form_schema', sa.JSON(), nullable=True, comment='表单字段定义'),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('clone_from_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing_page')),
    sa.UniqueConstraint('slug', name=op.f('uq_landing_page_slug'))
    )
    op.create_table('license',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('license_key', sa.String(length=128), nullable=False),
    sa.Column('edition', sa.String(length=16), nullable=False, comment='trial/standard/flagship'),
    sa.Column('customer_name', sa.String(length=128), nullable=True),
    sa.Column('user_quota', sa.Integer(), nullable=False),
    sa.Column('mail_quota', sa.Integer(), nullable=False),
    sa.Column('sms_quota', sa.Integer(), nullable=False),
    sa.Column('campaign_quota', sa.Integer(), nullable=False),
    sa.Column('activate_mode', sa.String(length=8), nullable=True, comment='online/offline'),
    sa.Column('signature', sa.Text(), nullable=True, comment='离线lic RSA签名'),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False, comment='active/expired/revoked'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license'))
    )
    op.create_table('license_usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('mails_sent', sa.Integer(), nullable=False),
    sa.Column('sms_sent', sa.Integer(), nullable=False),
    sa.Column('campaigns_created', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_usage')),
    sa.UniqueConstraint('stat_date', name=op.f('uq_license_usage_stat_date'))
    )
    op.create_table('login_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('login_type', sa.String(length=16), nullable=False, comment='local/sso_oidc/sso_cas/ldap'),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('fail_reason', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_log'))
    )
    op.create_index(op.f('ix_login_log_account_id'), 'login_log', ['account_id'], unique=False)
    op.create_table('mail_report',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False, comment='outlook_plugin/webmail/manual/api'),
    sa.Column('reporter_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reporter_email', sa.String(length=128), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('from_addr', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('eml_path', sa.String(length=512), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False, comment='pending/drill/real_phishing/false_positive/spam'),
    sa.Column('classifier', sa.String(length=8), nullable=True, comment='auto/manual'),
    sa.Column('matched_campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('handler_id', sa.BigInteger(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('handle_remark', sa.String(length=512), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_report'))
    )
    op.create_index(op.f('ix_mail_report_classification'), 'mail_report', ['classification'], unique=False)
    op.create_index(op.f('ix_mail_report_reporter_user_id'), 'mail_report', ['reporter_user_id'], unique=False)
    op.create_table('open_api_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('req_body', sa.Text(), nullable=True),
    sa.Column('resp_body', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_api_log'))
    )
    op.create_index(op.f('ix_open_api_log_app_id'), 'open_api_log', ['app_id'], unique=False)
    op.create_table('open_app',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=32), nullable=False),
    sa.Column('app_secret_enc', sa.LargeBinary(), nullable=False, comment='AES-GCM加密'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False, comment='campaign/user/template/report/mail_report/system'),
    sa.Column('ip_whitelist', sa.JSON(), nullable=True),
    sa.Column('callback_url', sa.String(length=255), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=False, comment='次/分钟'),
    sa.Column('status', sa.String(length=12), nullable=False, comment='active/disabled'),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_app')),
    sa.UniqueConstraint('app_id', name=op.f('uq_open_app_app_id'))
    )
    op.create_table('org_sync_job',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False, comment='ldap/wecom/dingtalk/feishu'),
    sa.Column('config_enc', sa.LargeBinary(), nullable=True, comment='连接配置加密'),
    sa.Column('cron', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_sync_job'))
    )
    op.create_table('phish_domain',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('spf_status', sa.String(length=8), nullable=False, comment='ok/fail/unknown'),
    sa.Column('dkim_status', sa.String(length=8), nullable=False),
    sa.Column('dmarc_status', sa.String(length=8), nullable=False),
    sa.Column('mx_status', sa.String(length=8), nullable=False),
    sa.Column('deliver_score', sa.Integer(), nullable=False, comment='送达评分0-100'),
    sa.Column('repair_tips', sa.Text(), nullable=True),
    sa.Column('dkim_selector', sa.String(length=32), nullable=False),
    sa.Column('dkim_public_key', sa.Text(), nullable=True),
    sa.Column('dkim_private_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phish_domain')),
    sa.UniqueConstraint('domain', name=op.f('uq_phish_domain_domain'))
    )
    op.create_table('platform_setting',
    sa.Column('setting_key', sa.String(length=64), nullable=False, comment='logo/name/copyright/pixel_enabled/retention_days/disclaimer/ai_switches'),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('setting_key', name=op.f('pk_platform_setting'))
    )
    op.create_table('qr_asset',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('landing_page_id', sa.BigInteger(), nullable=False),
    sa.Column('short_code', sa.String(length=12), nullable=False),
    sa.Column('img_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_asset')),
    sa.UniqueConstraint('short_code', name=op.f('uq_qr_asset_short_code'))
    )
    op.create_table('report_reward_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_reward_log'))
    )
    op.create_index(op.f('ix_report_reward_log_user_id'), 'report_reward_log', ['user_id'], unique=False)
    op.create_table('send_channel',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False, comment='smtp/ews/sms'),
    sa.Column('smtp_host', sa.String(length=128), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_encrypt', sa.String(length=12), nullable=True, comment='starttls/ssl/none'),
    sa.Column('smtp_username', sa.String(length=128), nullable=True),
    sa.Column('smtp_password_enc', sa.LargeBinary(), nullable=True, comment='AES-GCM加密'),
    sa.Column('ews_url', sa.String(length=255), nullable=True),
    sa.Column('ews_username', sa.String(length=128), nullable=True),
    sa.Column('ews_password_enc', sa.LargeBinary(), nullable=True),
    sa.Column('ews_auth_mode', sa.String(length=8), nullable=True, comment='basic/oauth2'),
    sa.Column('oauth_client_id', sa.String(length=128), nullable=True),
    sa.Column('oauth_client_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('oauth_tenant_id', sa.String(length=128), nullable=True),
    sa.Column('sms_provider', sa.String(length=16), nullable=True, comment='aliyun/tencent/huawei/netease/custom_http/serial_4g'),
    sa.Column('sms_api_url', sa.String(length=255), nullable=True),
    sa.Column('sms_sign', sa.String(length=64), nullable=True),
    sa.Column('sms_key', sa.String(length=128), nullable=True),
    sa.Column('sms_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('sms_template_id', sa.String(length=64), nullable=True),
    sa.Column('serial_port', sa.String(length=64), nullable=True),
    sa.Column('baud_rate', sa.Integer(), nullable=True),
    sa.Column('sim_number', sa.String(length=32), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=False, comment='每日上限,超限顺延'),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False, comment='normal/abnormal/disabled'),
    sa.Column('last_test_result', sa.JSON(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_send_channel'))
    )
    op.create_table('send_quota_usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_send_quota_usage')),
    sa.UniqueConstraint('channel_id', 'stat_date', name='uq_quota_channel_date')
    )
    op.create_table('sender_profile',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel_type', sa.String(length=8), nullable=False, comment='mail/sms'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='发件人显示名称'),
    sa.Column('from_addr', sa.String(length=128), nullable=True, comment='发件邮箱(需绑定已配域名)'),
    sa.Column('reply_to', sa.String(length=128), nullable=True),
    sa.Column('sms_number', sa.String(length=32), nullable=True),
    sa.Column('sms_sign', sa.String(length=64), nullable=True),
    sa.Column('scene_tags', sa.JSON(), nullable=True, comment='["finance","hr","system","holiday","prize","security"]'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sender_profile'))
    )
    op.create_table('siem_config',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False, comment='cef/json'),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_siem_config'))
    )
    op.create_table('stat_daily',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('dim_type', sa.String(length=16), nullable=False, comment='platform/dept/scene/user'),
    sa.Column('dim_id', sa.BigInteger(), nullable=True, comment='部门ID/用户ID'),
    sa.Column('dim_key', sa.String(length=32), nullable=True, comment='场景标签'),
    sa.Column('campaign_cnt', sa.Integer(), nullable=False),
    sa.Column('target_cnt', sa.Integer(), nullable=False),
    sa.Column('delivered_cnt', sa.Integer(), nullable=False),
    sa.Column('open_cnt', sa.Integer(), nullable=False),
    sa.Column('click_cnt', sa.Integer(), nullable=False),
    sa.Column('submit_cnt', sa.Integer(), nullable=False),
    sa.Column('report_cnt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stat_daily')),
    sa.UniqueConstraint('stat_date', 'dim_type', 'dim_id', 'dim_key', name='uq_stat_daily_dim')
    )
    op.create_index(op.f('ix_stat_daily_stat_date'), 'stat_daily', ['stat_date'], unique=False)
    op.create_table('sys_account',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('emp_user_id', sa.BigInteger(), nullable=True, comment='可选:关联员工档案'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1启用 0禁用'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_account')),
    sa.UniqueConstraint('username', name=op.f('uq_sys_account_username'))
    )
    op.create_table('sys_account_role',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('account_id', 'role_id', name=op.f('pk_sys_account_role'))
    )
    op.create_table('sys_permission',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('perm_code', sa.String(length=128), nullable=False, comment='如 campaign:create'),
    sa.Column('type', sa.Integer(), nullable=False, comment='1菜单 2按钮 3接口'),
    sa.Column('route', sa.String(length=128), nullable=True, comment='前端路由'),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission')),
    sa.UniqueConstraint('perm_code', name=op.f('uq_sys_permission_perm_code'))
    )
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='super_admin/operator/auditor'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('data_scope', sa.Integer(), nullable=False, comment='1全部 2本部门及子级 3本部门 4仅本人 5自定义'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role')),
    sa.UniqueConstraint('code', name=op.f('uq_sys_role_code'))
    )
    op.create_table('sys_role_dept',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('dept_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'dept_id', name=op.f('pk_sys_role_dept'))
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_sys_role_permission'))
    )
    op.create_table('track_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=12), nullable=False, comment='open/click/submit/report/attach_run/bounce'),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.String(length=512), nullable=True),
    sa.Column('fingerprint_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True, comment='脱敏后:字段名集合/长度/链接/耗时'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_event'))
    )
    op.create_index(op.f('ix_track_event_campaign_id'), 'track_event', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_track_event_event_type'), 'track_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_track_event_user_id'), 'track_event', ['user_id'], unique=False)
    op.create_table('training_assignment',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False, comment='0-100'),
    sa.Column('status', sa.String(length=12), nullable=False, comment='pending/learning/completed/overdue'),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_assignment'))
    )
    op.create_index(op.f('ix_training_assignment_task_id'), 'training_assignment', ['task_id'], unique=False)
    op.create_index(op.f('ix_training_assignment_user_id'), 'training_assignment', ['user_id'], unique=False)
    op.create_table('training_task',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False, comment='manual/campaign'),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('audience', sa.JSON(), nullable=False, comment='人群快照:部门/分组/标签/用户ID'),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False, comment='active/closed'),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_task'))
    )
    op.create_table('webhook_config',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('im_type', sa.String(length=12), nullable=True, comment='wecom/dingtalk/feishu/custom'),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=False, comment='campaign_done/high_risk/new_real_phish...'),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_config'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_config')
    op.drop_table('training_task')
    op.drop_index(op.f('ix_training_assignment_user_id'), table_name='training_assignment')
    op.drop_index(op.f('ix_training_assignment_task_id'), table_name='training_assignment')
    op.drop_table('training_assignment')
    op.drop_index(op.f('ix_track_event_user_id'), table_name='track_event')
    op.drop_index(op.f('ix_track_event_event_type'), table_name='track_event')
    op.drop_index(op.f('ix_track_event_campaign_id'), table_name='track_event')
    op.drop_table('track_event')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_role_dept')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('sys_account_role')
    op.drop_table('sys_account')
    op.drop_index(op.f('ix_stat_daily_stat_date'), table_name='stat_daily')
    op.drop_table('stat_daily')
    op.drop_table('siem_config')
    op.drop_table('sender_profile')
    op.drop_table('send_quota_usage')
    op.drop_table('send_channel')
    op.drop_index(op.f('ix_report_reward_log_user_id'), table_name='report_reward_log')
    op.drop_table('report_reward_log')
    op.drop_table('qr_asset')
    op.drop_table('platform_setting')
    op.drop_table('phish_domain')
    op.drop_table('org_sync_job')
    op.drop_table('open_app')
    op.drop_index(op.f('ix_open_api_log_app_id'), table_name='open_api_log')
    op.drop_table('open_api_log')
    op.drop_index(op.f('ix_mail_report_reporter_user_id'), table_name='mail_report')
    op.drop_index(op.f('ix_mail_report_classification'), table_name='mail_report')
    op.drop_table('mail_report')
    op.drop_index(op.f('ix_login_log_account_id'), table_name='login_log')
    op.drop_table('login_log')
    op.drop_table('license_usage')
    op.drop_table('license')
    op.drop_table('landing_page')
    op.drop_index(op.f('ix_landing_form_field_page_id'), table_name='landing_form_field')
    op.drop_table('landing_form_field')
    op.drop_table('fingerprint')
    op.drop_index(op.f('ix_exam_record_user_id'), table_name='exam_record')
    op.drop_index(op.f('ix_exam_record_paper_id'), table_name='exam_record')
    op.drop_table('exam_record')
    op.drop_table('exam_question')
    op.drop_table('exam_paper_question')
    op.drop_table('exam_paper')
    op.drop_table('emp_user_tag')
    op.drop_index(op.f('ix_emp_user_dept_id'), table_name='emp_user')
    op.drop_table('emp_user')
    op.drop_table('emp_tag')
    op.drop_table('emp_risk_profile')
    op.drop_table('emp_group_member')
    op.drop_table('emp_group')
    op.drop_table('emp_dept')
    op.drop_table('email_template')
    op.drop_table('course')
    op.drop_index(op.f('ix_campaign_target_user_id'), table_name='campaign_target')
    op.drop_index(op.f('ix_campaign_target_campaign_id'), table_name='campaign_target')
    op.drop_table('campaign_target')
    op.drop_table('campaign_stat')
    op.drop_index(op.f('ix_campaign_batch_campaign_id'), table_name='campaign_batch')
    op.drop_table('campaign_batch')
    op.drop_index(op.f('ix_campaign_alert_campaign_id'), table_name='campaign_alert')
    op.drop_table('campaign_alert')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_schedule_at'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_creator_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_audit_log_module'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_account_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('attachment_payload')
    op.drop_index(op.f('ix_attachment_download_log_payload_id'), table_name='attachment_download_log')
    op.drop_table('attachment_download_log')
    op.drop_table('ai_usage_stat')
    op.drop_index(op.f('ix_ai_session_account_id'), table_name='ai_session')
    op.drop_table('ai_session')
    op.drop_table('ai_provider')
    op.drop_index(op.f('ix_ai_message_session_id'), table_name='ai_message')
    op.drop_table('ai_message')
    op.drop_index(op.f('ix_ai_draft_biz_type'), table_name='ai_draft')
    op.drop_table('ai_draft')
    # ### end Alembic commands ###
