"""landing_page 自定义路径（仿真防识别）

Revision ID: bdfe7e3fa834
Revises: 63f9409271e0
Create Date: 2026-08-26 23:08:44.550347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfe7e3fa834'
down_revision: Union[str, None] = '63f9409271e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landing_page', sa.Column('custom_path', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_landing_page_custom_path'), 'landing_page', ['custom_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_landing_page_custom_path'), 'landing_page', type_='unique')
    op.drop_column('landing_page', 'custom_path')
    # ### end Alembic commands ###
