"""service display columns

Revision ID: 8452d09fcd36
Revises: 1cb3bdd0fa3e
Create Date: 2026-08-16 19:16:52.173316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8452d09fcd36'
down_revision: Union[str, None] = '1cb3bdd0fa3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment_payload', sa.Column('platform', sa.String(length=64), nullable=True, comment='目标平台 Windows/macOS/Linux'))
    op.add_column('attachment_payload', sa.Column('evade_rate', sa.Integer(), nullable=False, comment='检测逃逸率%'))
    op.add_column('attachment_payload', sa.Column('used_count', sa.Integer(), nullable=False))
    op.add_column('attachment_payload', sa.Column('status', sa.String(length=12), nullable=False, comment='enabled/disabled'))
    op.add_column('attachment_payload', sa.Column('icon', sa.String(length=8), nullable=True, comment='列表展示图标'))
    op.add_column('course', sa.Column('level', sa.String(length=8), nullable=False, comment='easy/mid/hard'))
    op.add_column('course', sa.Column('material', sa.String(length=64), nullable=True, comment='课件形态：视频课件/图文+PDF/场景模拟等'))
    op.add_column('email_template', sa.Column('sender', sa.String(length=128), nullable=True, comment='建议发件人显示名'))
    op.add_column('email_template', sa.Column('stars', sa.Integer(), nullable=False, comment='难度星级 1-5'))
    op.add_column('email_template', sa.Column('used_count', sa.Integer(), nullable=False))
    op.add_column('email_template', sa.Column('click_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='平均点击率%'))
    op.add_column('exam_question', sa.Column('course_id', sa.BigInteger(), nullable=True, comment='关联课程'))
    op.create_index(op.f('ix_exam_question_course_id'), 'exam_question', ['course_id'], unique=False)
    op.add_column('landing_page', sa.Column('used_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landing_page', 'used_count')
    op.drop_index(op.f('ix_exam_question_course_id'), table_name='exam_question')
    op.drop_column('exam_question', 'course_id')
    op.drop_column('email_template', 'click_rate')
    op.drop_column('email_template', 'used_count')
    op.drop_column('email_template', 'stars')
    op.drop_column('email_template', 'sender')
    op.drop_column('course', 'material')
    op.drop_column('course', 'level')
    op.drop_column('attachment_payload', 'icon')
    op.drop_column('attachment_payload', 'status')
    op.drop_column('attachment_payload', 'used_count')
    op.drop_column('attachment_payload', 'evade_rate')
    op.drop_column('attachment_payload', 'platform')
    # ### end Alembic commands ###
