"""fingerprint_detail

Revision ID: eb9f27dbc830
Revises: 0ce125ae1978
Create Date: 2026-08-22 11:33:28.732631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9f27dbc830'
down_revision: Union[str, None] = '0ce125ae1978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fingerprint', sa.Column('detail', sa.JSON(), nullable=True, comment='首次采集的原始组件：分辨率/GPU/字体/语言/时区等'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fingerprint', 'detail')
    # ### end Alembic commands ###
