"""exam_paper_publish_audience

Revision ID: 0ce125ae1978
Revises: 7f3a1b9c2d4e
Create Date: 2026-08-21 16:18:11.944620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce125ae1978'
down_revision: Union[str, None] = '7f3a1b9c2d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_paper', sa.Column('publish_audience', sa.JSON(), nullable=True, comment='发布对象人群快照:all/dept_ids/user_ids+labels'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_paper', 'publish_audience')
    # ### end Alembic commands ###
