"""campaign_target_fail_reason

Revision ID: af400606d2a8
Revises: eb9f27dbc830
Create Date: 2026-08-23 07:21:16.749400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af400606d2a8'
down_revision: Union[str, None] = 'eb9f27dbc830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_target', sa.Column('fail_reason', sa.String(length=500), nullable=True, comment='投递失败原因（SMTP 拒收/认证失败/超时等）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_target', 'fail_reason')
    # ### end Alembic commands ###
