"""sender_profile channel_id

Revision ID: c34aa729af7c
Revises: 3afe38a93073
Create Date: 2026-08-19 23:55:10.792081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c34aa729af7c'
down_revision: Union[str, None] = '3afe38a93073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emp_risk_profile', 'risk_level',
               existing_type=mysql.INTEGER(),
               comment='1低(0-70) 2中(71-80) 3高(81-100)',
               existing_comment='1低(0-30) 2中(31-70) 3高(71-100)',
               existing_nullable=False)
    op.add_column('sender_profile', sa.Column('channel_id', sa.BigInteger(), nullable=True, comment='关联发送通道ID，空=用默认SMTP通道'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sender_profile', 'channel_id')
    op.alter_column('emp_risk_profile', 'risk_level',
               existing_type=mysql.INTEGER(),
               comment='1低(0-30) 2中(31-70) 3高(71-100)',
               existing_comment='1低(0-70) 2中(71-80) 3高(81-100)',
               existing_nullable=False)
    # ### end Alembic commands ###
