"""ix: track_event.created_at, campaign_target(send_status,sent_at), emp_risk_profile.phish_count

Revision ID: 68fd1f123734
Revises: af400606d2a8
Create Date: 2026-08-23 23:54:00.298374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68fd1f123734'
down_revision: Union[str, None] = 'af400606d2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_campaign_target_send_status_sent_at', 'campaign_target', ['send_status', 'sent_at'], unique=False)
    op.alter_column('emp_risk_profile', 'phish_count',
               existing_type=mysql.INTEGER(),
               comment='历史中招次数（高危榜排序）',
               existing_comment='历史中招次数',
               existing_nullable=False)
    op.create_index(op.f('ix_emp_risk_profile_phish_count'), 'emp_risk_profile', ['phish_count'], unique=False)
    op.create_index(op.f('ix_track_event_created_at'), 'track_event', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_event_created_at'), table_name='track_event')
    op.drop_index(op.f('ix_emp_risk_profile_phish_count'), table_name='emp_risk_profile')
    op.alter_column('emp_risk_profile', 'phish_count',
               existing_type=mysql.INTEGER(),
               comment='历史中招次数',
               existing_comment='历史中招次数（高危榜排序）',
               existing_nullable=False)
    op.drop_index('ix_campaign_target_send_status_sent_at', table_name='campaign_target')
    # ### end Alembic commands ###
